export enum CmsDataKey {
  HERO_SLIDES = "hero_slides",
  HERO_SUBTITLE = "hero_subtitle",
  HERO_BTN_TEXT = "hero_btn_text",
  HERO_LAYOUT = "hero_layout",
  HERO_BG_STYLE = "hero_bg_style",
  HERO_TITLE = "hero_title",
  HERO_DESC = "hero_desc",
  HERO_IMAGE_URL = "hero_image_url",
  HERO_BANNER_TYPE = "hero_banner_type",
  HERO_VIDEO_URL = "hero_video_url",
  HERO_VIDEO_EYEBROW = "hero_video_eyebrow",
  HERO_VIDEO_BTN_TEXT = "hero_video_btn_text",
  HERO_VIDEO_TITLE = "hero_video_title",
  HERO_VIDEO_BTN_LINK = "hero_video_btn_link",
  HERO_VIDEO_DESC = "hero_video_desc",
  
  MIDDLE_BANNER_SUBTITLE = "middle_banner_subtitle",
  MIDDLE_BANNER_BTN_TEXT = "middle_banner_btn_text",
  MIDDLE_BANNER_TITLE = "middle_banner_title",
  MIDDLE_BANNER_DESC = "middle_banner_desc",
  MIDDLE_BANNER_IMAGE_URL = "middle_banner_image_url",
  
  NEWSLETTER_TITLE = "newsletter_title",
  NEWSLETTER_BTN_TEXT = "newsletter_btn_text",
  NEWSLETTER_EYEBROW = "newsletter_eyebrow",
  NEWSLETTER_SUCCESS_TEXT = "newsletter_success_text",
  NEWSLETTER_DESC = "newsletter_desc",
  NEWSLETTER_DISCLAIMER = "newsletter_disclaimer",
  
  BRAND_HIGHLIGHT_EYEBROW = "brand_highlight_eyebrow",
  BRAND_HIGHLIGHT_BTN_TEXT = "brand_highlight_btn_text",
  BRAND_HIGHLIGHT_TITLE = "brand_highlight_title",
  BRAND_HIGHLIGHT_DESC = "brand_highlight_desc",
  BRAND_HIGHLIGHT_IMAGE_URL = "brand_highlight_image_url",
  BRAND_HIGHLIGHT_BG_COLOR = "brand_highlight_bg_color",
  
  LOOKBOOK_TITLE = "lookbook_title",
  LOOKBOOK_SUBTITLE = "lookbook_subtitle",
  LOOKBOOK_IMAGE_URL = "lookbook_image_url",
  LOOKBOOK_BG_COLOR = "lookbook_bg_color",
  LOOKBOOK_HOTSPOTS = "lookbook_hotspots",
  
  SCARCITY_TIMER_TITLE = "scarcity_timer_title",
  SCARCITY_EXPIRES_AT = "scarcity_expires_at",
  SCARCITY_BTN_TEXT = "scarcity_btn_text",
  SCARCITY_BTN_LINK = "scarcity_btn_link",
  SCARCITY_ALERT_TEXT = "scarcity_alert_text",
  SCARCITY_ALERT_BG = "scarcity_alert_bg",
  SCARCITY_ALERT_TEXT_COLOR = "scarcity_alert_text_color",
  
  SOCIAL_PROOF_TITLE = "social_proof_title",
  SOCIAL_PROOF_EYEBROW = "social_proof_eyebrow",
  SOCIAL_PROOF_TESTIMONIALS = "social_proof_testimonials",
  SOCIAL_PROOF_BADGES = "social_proof_badges",
  
  CURATED_TITLE = "curated_title",
  CURATED_SUBTITLE = "curated_subtitle",
  CURATED_TYPE = "curated_type",
  CURATED_PRODUCT_IDS = "curated_product_ids",
  CURATED_BG_COLOR = "curated_bg_color",

  PROMO_TIMER_TITLE = "promo_timer_title",
  PROMO_EXPIRES_AT = "promo_expires_at",
  PROMO_ALERT_TEXT = "promo_alert_text",
  PROMO_ALERT_BG = "promo_alert_bg",
  PROMO_ALERT_TEXT_COLOR = "promo_alert_text_color",
  PROMO_BTN_TEXT = "promo_btn_text",
  PROMO_BTN_LINK = "promo_btn_link",

  // For useHomepageData internal keys
  BANNERS_CACHE_KEY = "homepage_banners",
  CATEGORIES_CACHE_KEY = "homepage_categories",
  CMS_CACHE_KEY = "homepage_cms",
  LANG_KEY = "user_lang",
}

export enum LayoutSection {
  HERO = "hero",
  CATEGORIES = "categories",
  PRODUCTS = "products",
  PROMO = "promo",
  NEW_ARRIVALS = "new_arrivals",
  NEWSLETTER = "newsletter",
  LOOKBOOK = "lookbook",
  SCARCITY = "scarcity",
  SOCIAL_PROOF = "social_proof",
  CURATED = "curated",
}
